### PR TITLE
Dinoloket read method

### PR DESCRIPTION
**Pull request by tomvansteijn**
# Short Description
Added support for reading river level gauges in Dinoloket format. Changes in pastas\read\Dinoloket.py and a simple read test.

# Checklist before PR can be merged:
- [x] closes issue #204
- [x] is documented
- [x] PEP8 compliant code
- [x] tests added / passed
- [x] passes Travis
- [x] Example Notebook (for new features)

### CODE REVIEW

**Comment by tomvansteijn** [comment]
Ofcourse codacy does not like the duplication in my code. Which is deliberate because I did not want to diverge from the coding style in the original reader class for groundwater levels.

A previous attempt is available in [this branch](https://github.com/tomvansteijn/pastas/blob/dev-read-dinoloket/pastas/read/dinoloket.py). No duplication, but this contains breaking changes.

**Comment by dbrakenhoff** [comment]
I think you need to change the filepaths in the notebook to use the forward slash instead of backslash for the tests to pass.

**Comment by raoulcollenteur** [comment]
@dbrakenhoff can you check the PR? I'll make a new Pastas version the end of this week, would be great if we can add this to the new version!

**Comment by dbrakenhoff** [comment]
As Tom already mentioned, there's a lot of duplication, but that is unavoidable. I figured the notebook would be a good place to elaborate on all the read methods currently in Pastas, so I made some initial changes so the examples for KNMI, Waterbase can be added later. 

p.s. Waterbase was replaced by waterinfo as far as I know. And I don't know if read.waterbase is also capable of reading rws.waterinfo.nl files...? Something to look into.

**Comment by dbrakenhoff** [comment]
Once travis passes, I will merge.

**Pull request merged**
