### PR TITLE
428 models compare

### PR DESCRIPTION
**Pull request by dbrakenhoff**
# Short Description
Add a ModelComparison class as proposed in #428.

# Checklist before PR can be merged:
- [x] closes issue #428
- [x] is documented
- [x] PEP8 compliant code
- [x] tests added / passed
- [x] Example Notebook (for new features)
- [ ] API changes documented in Release Notes

### CODE REVIEW

**Comment by martinvonk** [comment]
This PR can now be reviewed.

Last changes that I made are to the `pastas.plots.compare` function. I did not want to deprecate it, so now it returns the Axes dictionary of the `ModelComparison` plot. If a user wants to change the `tmin `or `tmax`, an Axes object can be called from the dictionary and `set_xlim()` can to be used.

**Comment by raoulcollenteur** [comment]
couple of warnings from GH CI on matplotlib join use: https://github.com/pastas/pastas/actions/runs/3273691774/jobs/5386228017

perhaps check that? Won't work soon anymore otherwise.

**Comment by dbrakenhoff** [comment]
https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#groupers-from-get-shared-x-axes-get-shared-y-axes-will-be-immutable

Should be easy enough to fix, I'll take a look

**Comment by dbrakenhoff** [comment]
This should be good to go now! 

Question: since we're autogenerating the release notes these days, is the final PR step still necessary?

**Comment by raoulcollenteur** [comment]
> This should be good to go now!
> 
> Question: since we're autogenerating the release notes these days, is the final PR step still necessary?

Agreed, last point is not necessary anymore, I'll remove it!

**Review by raoulcollenteur — APPROVED** [review]

**Comment by raoulcollenteur** [comment]
Looks good to go to me. I fixed most of the CI errors. There are a couple left in plots_comparison.py. Could you have a look and fix those? I already approved the PR, so after you can merge :)

Nice work!

Cheers,
Raoul

**Pull request merged**
