### PR TITLE
Uncertainty estimation example notebook

### PR DESCRIPTION
**Pull request by mbakker7**
# Short Description
The notebook pastas_uncertainty_benchmarks in the doc/benchmarks folder presents an analysis of the coverage of the uncertainty interval for the estimated parameters using synthetic data. 

# Checklist before PR can be merged:
- [x] Format code with [ruff formatting](https://docs.astral.sh/ruff/)
- [X] Benchmark Notebook
- [ ] Remove output for all notebooks with changes

### CODE REVIEW

**Comment by martinvonk** [comment]
> Ruff still complains about something, but I don't understand what. Seems like some import sequence. @martinvonk, do you have an idea?

Ill have a look

**Comment by mbakker7** [comment]
The notebook takes too long to run (not surprisingly - on my computer it takes 5 - 10 minutes). 
Gotta skip the notebook when testing.

**Comment by martinvonk** [comment]
> The notebook takes too long to run (not surprisingly - on my computer it takes 5 - 10 minutes). Gotta skip the notebook when testing.

The benchmark notebooks are not tested for every pull request. Only pull requests to the `master` branch, i.e. on releases, the benchmark notebooks are tested. So I guess it is fine if it takes a while?

**Comment by mbakker7** [comment]
Ready to merge IMHO

**Review by raoulcollenteur — APPROVED** [review]

**Pull request merged**
