### PR TITLE
Add empty StressModel2 that raises warning [closes #363]

### LINKED ISSUE #363: Deprecate StressModel2 in v0.21.0, remove in v0.23.0
As discussed StressModel2 can be deprecated in v0.20.0

### PR DESCRIPTION
**Pull request by raoulcollenteur**
# Short Description

This PR temporarily reintroduces the StressModel2 for Pastas 0.22. The Stressmodel2 automatically returns a RechargeModel instance, and can be used to transform old pas-files with a StressModel2 object to the new format, and work in newer Pastas versions. In 0.23.0 the StressModel2 will not return an instance anymore but instead throw an Error telling the user to create a RechargeModel instance instead.

# Checklist before PR can be merged:
- [X] closes issue #363
- [X] PEP8 compliant code
- [x] tests added / passed
- [x] API changes documented in Release Notes

### CODE REVIEW

**Comment by mbakker7** [comment]
Looks good, but I think a 'DeprecationWarning' is confusing, as it doesn't work anymore. It should simply be an error. What so you think?

**Comment by raoulcollenteur** [comment]
> Looks good, but I think a 'DeprecationWarning' is confusing, as it doesn't work anymore. It should simply be an error. What so you think?

Agreed. Changed it to UserWarning now, I think that is more appropriate. Not sure what other error we could/should use..

**Comment by raoulcollenteur** [comment]
Updated the stressmodel to return a RechargeModel for Pastas 0.22, allowing conversion of old pas-files. Should be good to go! @mbakker7, @martinvonk, @rubencalje can on of you check?

**Review by martinvonk — APPROVED** [review]
solved merge conflict and removed capital letter. looks good to go.

**Pull request merged**
