### PR TITLE
Save and read options of FlexModel to/from pas-file

### PR DESCRIPTION
**Pull request by rubencalje**
# Short Description
This fix makes it possible to save the interception, snow and gw_uptake in a pas-file

# Checklist before PR can be merged:
- [ ] closes issue #xxxx
- [ ] is documented
- [ ] PEP8 compliant code
- [ ] tests added / passed
- [ ] Example Notebook (for new features)
- [ ] API changes documented in Release Notes

### CODE REVIEW

**Review by martinvonk — APPROVED** [review]
Happy this works!

**Comment by raoulcollenteur** [comment]
I see this is already closed, so this is just for future reference. Perhaps a to_dict method added to the recharge class would be cleaner approach with less redundancy (storing the same things twice). Then the RechargeModel could call the to_dict method, similar to the other objects in Pastas. But it's all internal methods so we could change that in the future.

**Comment by rubencalje** [comment]
It is true that the methods are all internal. But the way it is programmed now, an extra property is added to the representation of a stressmodel in a pas-file, called 'recharge_kwargs'. This is the only part that might be difficult to change in the future.

I could not thick of a to_dict way of implementing the storing of extra arguments while keeping backwards-compatibity with older pas-files. But maybe we can sort that out later.

**Comment by raoulcollenteur** [comment]
Ah yes, I meant only for writing the kwargs when storing a file (e.g., FlexModel.to_dict()). I think adding the 'recharge_kwargs' was necessary anyway so that makes sense. Anyway, happy it works now and we can adjust the rest easily in the future.

**Pull request merged**
