### PR TITLE
Improve testing routine and GitHub CI

### PR DESCRIPTION
**Pull request by dbrakenhoff**
# Short Description
Move linting out of testing step

Linting step checks:
- black formatting -> pass/fail
- isort formatting -> pass/fail
- flake8 -> always pass (but does show code style issues + statistics)

Testing step now only runs tests and notebooks.

### CODE REVIEW

**Comment by martinvonk** [comment]
I like this change, can we relate this (partially) to #509 ?

**Comment by martinvonk** [comment]
Really like this change. Thanks for the hard work on the ci.yml @dbrakenhoff :)

So with this change we can use _tox_ for testing all every change locally. Tox sets up virtual test environments locally (takes a bit of time the first time).
Run the formatting tests (black + isort) with: `tox -e format`
Run the linting tests (flake8) with: `tox -e lint`
Run pytest (without notebooks): `tox -e py38` (or `py39`, `py310 `for other python versions)
Run pytest (with notebooks): `tox -e notebooks`
The settings of these tests can be changed in `pyproject.toml` under `[tool.tox]`

GitHub actions uses tox to test the continuous integration also, giving a nice overview of the passing/failing of each specific test. In the future, building the docs (readthedocs) can also be done this way if we want. Same goes for static type checking with mypy.

This PR also adds the pytest.fixtures for different model types in the unit testing routine which is a nice improvement in terms of speed and test readability.

**Review by raoulcollenteur — APPROVED** [review]

**Comment by raoulcollenteur** [comment]
Oh this is fun I need to change to settings for this PR. Which checks should be passed for a PR to be merged? Until now RTD, Py38-310 were required. I need to adjust this in the settings.

**Comment by raoulcollenteur** [comment]
Just made everything "required", except for Coverage. Okay?

**Pull request merged**
