### PR TITLE
Add map with Pastas models to docs

### PR DESCRIPTION
**Pull request by raoulcollenteur**
# Short Description
Add a short description describing the pull request (PR) here.

# Checklist before PR can be merged:
- [x] closes issue #633 
- [x] tests added / passed

### CODE REVIEW

**Comment by raoulcollenteur** [comment]
I think we can actually merge this, as this PR only adds one page to the docs. The actual page is made in another repo and can be updated independently. 

The page can be viewed here: https://pastas--637.org.readthedocs.build/en/637/map.html

What do you all think?

**Comment by martinvonk** [comment]
Awesome! Maybe we can make the vertical (and maybe also horizontal) space of the map on the web page a bit larger. I'm having a bit of trouble navigating.

**Comment by dbrakenhoff** [comment]
Cool! Agree with Martin that it could use some styling but this is a good start!

FYI: some models are currently located in the Baltic Sea...

**Comment by raoulcollenteur** [comment]
Thanks! I am trying to remove the right sidebar now to increase the width, hopefully I used the right code now.  Let's see after RTD build finished. 

Over the next couple of weeks I will update the actual website, using the HTML plots from poorly @dbrakenhoff ;-)

**Comment by raoulcollenteur** [comment]
Worked! In addition I will make sure the sidebar will be toggled off by default so you only see the map :) Merging!

**Pull request merged**
