### PR TITLE
Keep first entry in noise

### PR DESCRIPTION
**Pull request by rubencalje**
This pull request addresses issue #152

### CODE REVIEW

**Comment by raoulcollenteur** [comment]
I am very, very strongly against this suggested change, as it fundamentally changes the objective function (to something that is wrong in my opinion and masking important underlying problems with the noise model and optimization).

If you want to use such a noise model I suggest to add a NoiseModel3 class or something similar, and write in the docstring that this is meant for testing).

**Comment by rubencalje** [comment]
ok, that is a bit dramatic. It is just one value, where we have no information on previous errors, so we assume all error is noise . Right now the first model error in time is ignored, which can cause a large residual for the rest of the simulation for a large value of noise-alpha. I think we should take the first error into account for our objective function, just like we do for residuals after a large gap in a measurement series. The noise-value just after the gap is then also equal to the residual.

In NoiseModel2 we already do this, so there is no point in adding another noisemodel.

**Comment by raoulcollenteur** [comment]
Also, the solution might be in a different objective function, for example by adding the average value of the residuals, but this is separate from the noise model.

**Comment by rubencalje** [comment]
> In NoiseModel2 we already do this, so there is no point in adding another noisemodel.

I see NoiseModel2 was changed. In the master-branch we keep the first residual as noise, like I want. In the develop-branch however, the first value of the Noise in NoiseModel2 is also set to 0...

**Pull request closed without merging**
