### PR TITLE
Update the Pastas readthedocs quick example

### PR DESCRIPTION
**Pull request by martinvonk**
# Short Description
Pastas had a few changes since the last quick example so I updated the quick example code snippet and figure output.

### CODE REVIEW

**Review by dbrakenhoff — APPROVED** [review]
Isn't adding type hinting in this snippet a little bit overkill and maybe even confusing to less python-savvy users :)?

**Comment by martinvonk** [comment]
> Isn't adding type hinting in this snippet a little bit overkill and maybe even confusing to less python-savvy users :)?

Maybe yes, but on the other side it is clear what date types we expect. Type hints in the end are just a form of documentation.

I was also thinking about:
```python
data = pd.read_csv("observations.csv", index_col="datetime", parse_dates=["datetime"])
obs = data["head"]
prec = data["prec"]
evap = data["evap"]
```
which might feel more intuitive. Or with type hints:

```python
data: pd.DataFrame = pd.read_csv("observations.csv", index_col="datetime", parse_dates=["datetime"])
obs: pd.Series = data["head"]
prec: pd.Series = data["prec"]
evap: pd.Series = data["evap"]
```

**Comment by raoulcollenteur** [comment]
I think the Type hints are a little too much for an intro code snippet, so I'd be in favor of removing those.

Otherwise I think it is fine as is. I am in favor of keeping all examples with pd.Series though, because it is easier to teach things in one specific way, then multiple ways that (might) work..

**Review by raoulcollenteur — APPROVED** [review]

**Comment by raoulcollenteur** [comment]
Fine to merge after removing the type hints

**Comment by martinvonk** [comment]
```python
# Import Python packages
import pandas as pd
import pastas as ps

# Load head and meteorological observations into a pandas Series
obs = pd.read_csv("head.csv", index_col="datetime", parse_dates=["datetime"]).squeeze()
prec = pd.read_csv("prec.csv", index_col="datetime", parse_dates=["datetime"]).squeeze()
evap = pd.read_csv("evap.csv", index_col="datetime", parse_dates=["datetime"]).squeeze()

# Create and calibrate Pastas model
ml = ps.Model(obs, name="head")
sm = ps.RechargeModel(prec, evap, rfunc=ps.Exponential(), name="recharge")
ml.add_stressmodel(sm)
ml.solve()

# Visualize the model results
ml.plots.results()
```

**Pull request merged**
