### PR TITLE
Add Plotly plots and extension registration

### PR DESCRIPTION
**Pull request by dbrakenhoff**
# Short Description
This is a draft PR to preview how custom extensions can be registered to the Model class.

This PR adds Plotly plots to the Model class. 

Usage:
```python

# given some model ml
ml = ps.Model(...)
# ... build and optimize model ...

# register extension
ps.extensions.register_plotly()

# plot interactive results figure using plotly
ml.plotly.results()
```
Output
image

# Checklist before PR can be merged:
- [x] somewhat linked to #638 
- [x] is documented
- [x] Format code with [Black formatting](https://black.readthedocs.io)
- [x] type hints for functions and methods
- [x] tests added / passed
- [x] Example Notebook (for new features)
- [x] Remove output for all notebooks with changes

### CODE REVIEW

**Comment by dbrakenhoff** [comment]
Since this is a major development, I'd like multiple people to take a look and review this PR. Hence my request to you all :innocent:. 

This PR has two goals:
* The method by which extensions can be registered to existing classes. In this case the plotly class is available within pastas, but this could also be added from a separate repository. In that case, the `pastas.extensions.register_model_accessor()` decorator is used to decorate the new extension class. Once it is imported, the class will be available in the model object.
* Adding interactive plotting with plotly. Plotly is an optional dependency and only necessary when calling `ps.extensions.register_plotly()`. The notebook `plotly_interactive_plots.ipynb` shows the interactive figures.

**Comment by OnnoEbbens** [comment]
I still had an error when one of the contributions is close to zero. I will try to add this on Monday so maybe we can wait till then with the review?

**Comment by dbrakenhoff** [comment]
> I still had an error when one of the contributions is close to zero. I will try to add this on Monday so maybe we can wait till then with the review?

Did you get an actual error or weird looking output? Because I've noticed that occasionally that the code to determine the height ratios seems to fail and plots start overlapping. I can't seem to find an example at the moment however, so I was planning to address that when I ran into that issue again.

**Comment by OnnoEbbens** [comment]
It was an actual error that I had to catch using a try/except

**Comment by OnnoEbbens** [comment]
model with error: [test.zip](https://github.com/pastas/pastas/files/13488194/test.zip)

**Review by raoulcollenteur — APPROVED** [review]

**Comment by raoulcollenteur** [comment]
Looks good to me! I think we can merge this as well.

**Comment by dbrakenhoff** [comment]
I see you changed the milestone, @raoulcollenteur. Are we merging now, or after the release of 1.3? :)

**Comment by raoulcollenteur** [comment]
Oh my bad, let's merge and have this in 1.3!

**Pull request merged**
