### PR TITLE
Update master-branch to Pastas 1.0: Arrabiata

### PR DESCRIPTION
**Pull request by raoulcollenteur**
# Short Description

Preparing to update the master-branch to Pastas 1.0.

# Checklist before PR can be merged:
- [x] closes issue #421
- [x] is documented
- [x] Format code with [Black formatting](https://black.readthedocs.io)
- [x] type hints for functions and methods
- [x] tests added / passed
- [x] Example Notebook (for new features)
- [x] Remove output for all notebooks with changes

### CODE REVIEW

**Comment by raoulcollenteur** [comment]
Will check on the conflicting files after merging #502 into dev.

**Comment by raoulcollenteur** [comment]
This PR is ready (for review). I had to deal with the merge conflicts, so I chose the file from the dev-branch for all files, and then added the one line from 0.23.1 in again in the last commit.  @dbrakenhoff perhaps check this?

**Review by martinvonk — APPROVED** [review]

**Review by dbrakenhoff — APPROVED** [review]

**Comment by raoulcollenteur** [comment]
Thanks for the Reviews, I just updated the version and changed the status to stable. I will merge as soon as the check are completed.

**Comment by dbrakenhoff** [comment]
I fixed a few things codacy mentioned.

**Pull request merged**
