### PR TITLE
CONTRIBUTING.md:  point to the current dev site

### PR DESCRIPTION
**Pull request by dcslagel**
Update the url for for the developers section on the documentation site to point to the current location. 

The previous link goes to a 'page does not exist' page: (http://pastas.readthedocs.io/en/latest/developers.html)

Let me know if this change could be accepted (or rejected) or
needs some additional changes before being approved and merged.

Thank you,
DC

# Short Description
Add a short description describing the pull request (PR) here.

# Checklist before PR can be merged:
- [ ] closes issue #xxxx
- [ ] is documented
- [ ] PEP8 compliant code
- [x] tests added / passed
- [x] passes Travis
- [ ] Example Notebook (for new features)

### CODE REVIEW

**Comment by raoulcollenteur** [comment]
That works! Thanks DC for the PR, Merging it now :)
Cheers, Raoul

**Comment by raoulcollenteur** [comment]
Sorry, my previous response was too fast. The PR would merge into master, but we only allow PR that merge into the Dev-branch. Can you change the PR to merge into Dev? Other than that the PR is welcome!
Cheers,
Raoul

**Comment by dcslagel** [comment]
Hi @raoulcollenteur,

I changed the PR to request merge to the `dev` branch. 

Thanks,
DC

**Comment by raoulcollenteur** [comment]
Cool ! Merging the PR. Thanks for your contribution DC!

**Pull request merged**
