### PR TITLE
722 show estimated parameter uncertainties or not

### PR DESCRIPTION
**Pull request by OnnoEbbens**
# Short Description
Remove the estimated parameter uncertainties from the fit report and the model results plot by default. Add an optional argument to include the parameter uncertainties in both.

The estimated parameter uncertainties are only accurate estimates if some conditions are met. This is described in this notebook: https://pastas.readthedocs.io/en/master/examples/diagnostic_checking.html. To avoid people using the uncertainties while they are not accurate we remove them by default from some visuals. 

# Checklist before PR can be merged:
- [x] closes issue #722
- [x] is documented
- [x] Format code with [Black formatting](https://black.readthedocs.io)
- [x] type hints for functions and methods
- [x] tests added / passed

### CODE REVIEW

**Comment by rubencalje** [comment]
Maybe it is better to rename "par_uncertainty" to "stderr" or "par_stderr"?

**Comment by dbrakenhoff** [comment]
or just write it out entirely :)? `parameter_stderr`

**Comment by OnnoEbbens** [comment]
I renamed it to `stderr`

**Comment by mbakker7** [comment]
If I am not mistaken, none of the examples in the docs now show the stderr. But there are a few notebooks where we check the diagnostics. Those would be good notebooks to modify and show that the stderr can added (and the good workflow is then to do a diagnostics check first).

**Comment by OnnoEbbens** [comment]
You are correct, I've added the standard errors to the diagnostics and uncertainty notebooks. The standard error is also mentioned in the 'adding_trends' notebook (https://pastas.readthedocs.io/en/master/examples/adding_trends.html) for drawing a confidence interval. I think we can leave it like this. The only thing is that I don't see the confidence interval in the plot but that is another issue

**Comment by raoulcollenteur** [comment]
I think there are a couple more notebook where we can show the stderr. I know that for recharge estimation this is possible. I'll have a look at that after merging PR #678 . Otherwise I think this looks good!

**Pull request merged**
