### PR TITLE
Resolve Pandas 2.2 (FutureWarning) issues

### PR DESCRIPTION
**Pull request by martinvonk**
# Short Description

This PR solves many of the future warning for Pandas 2.2 in advance to 3.0.

Related to issue #629

### CODE REVIEW

**Comment by martinvonk** [comment]
You want to merge this @raoulcollenteur before #686? I was not able to fix the FutureWarnings yet. That takes more time.  But I did fix the failing test with Pandas. But if we merge this now, we can support more pandas versions in Pastas v1.4..

**Comment by martinvonk** [comment]
I added all FutureWarnings I found to #72. I have a feeling most things will be deprecated for Pandas 3.0 so we could add Pandas < 3.0 in the dependencies list.

**Comment by martinvonk** [comment]
Pandas 3.0 milestone is set for 1st of April: https://github.com/pandas-dev/pandas/milestone/102

**Comment by raoulcollenteur** [comment]
@martinvonk perhaps you can have a quick look at this? 

I also opened a new issue for Pandas 3.0 #687 to track changes necessary that only work with pandas > 2.1.

**Review by raoulcollenteur — APPROVED** [review]

**Pull request merged**
